apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gopoker
    server: etcd
  name: etcd-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gopoker
      server: etcd
  template:
    metadata:
      labels:
        app: gopoker
        server: etcd
    spec:
      containers:
        - image: appcelerator/etcd
          name: etcd-node
          ports:
            - containerPort: 2379

---
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  ports:
    - port: 2379
      targetPort: 2379
  selector:
    server: etcd