version: '3'
services:
  nats:
    image: nats
    ports:
      - 4222:4222
  etcd:
    image: appcelerator/etcd
    ports:
      - 2379:2379
#  corona-demo:
#    build: ../.
#    ports:
#      - 3333:3333
#    depends_on:
#      - nats
#      - etcd